# Generated by Django 3.0 on 2019-12-14 17:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('customer_phone', models.IntegerField()),
                ('customer_helth', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('period', models.IntegerField(choices=[(360, 'One Year'), (180, 'Six months'), (90, 'Three months')])),
                ('payment', models.IntegerField()),
                ('customer_sub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gymapp.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='VisitCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=datetime.datetime(2019, 12, 14, 17, 6, 5, 956639))),
                ('customer_visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gymapp.Subscription')),
            ],
        ),
    ]
